[project]
name = "chatlab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio>=5.29.0",
    "llama-stack-client>=0.2.4",
]
